administrator/urls.py
from django.urls import path
from . import views

app_name = "administrator"

urlpatterns = [
    path('login/', views.login),
    path('logout/', views.logout),
    path('registerAdmin/', views.register_admin),
    path('', views.Index.as_view(), name='index'),
    path('list/', views.ItemList.as_view(), name='item_list'),
    path('add/', views.ItemCreate.as_view(), name='item_add'),
    path('update/<int:pk>/', views.ItemUpdate.as_view(), name='item_update'),
    path('delete/<int:pk>/', views.ItemDelete.as_view(), name='item_delete'),
    path('item_detail/<int:pk>/', views.ItemDetail.as_view(), name='item_detail'),
    path('userlist/', views.UserList.as_view(), name='user_list'),
    path('userupdate/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('userdelete/<int:pk>/', views.UserDelete.as_view(), name='user_delete'),
    path('purchaselist/', views.PurchaseList.as_view(), name='purchase_list'),
    path('purchsedelete/<int:pk>/', views.PurchaseDelete.as_view(), name='purchase_delete'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from shopping import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('account/',include('account.urls')),
    path('shopping/',include('shopping.urls')),
    path('administrator/',include('administrator.urls', namespace='administrator')),
]

administrator/models.py
from django.db import models

# Create your models here.

class Admin(models.Model):

    admin_id = models.CharField(primary_key=True, max_length=128, unique=True) #PK
    password = models.CharField(max_length=256)

    def __str__(self):
        return self.admin_id #表示内容

    class Meta:
        ordering = ["-admin_id"] #並び順
        verbose_name = "管理者"
        verbose_name_plural = "管理者"

administrator/forms.py
from django import forms
from account.models import User

class UserForm(forms.Form):
    id = forms.CharField(label="管理者ID", max_length=128)
    password = forms.CharField(label="パスワード", max_length=256, widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    id = forms.CharField(label="管理者ID", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="パスワード", max_length=256, widget=forms.PasswordInput(render_value=True, attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="パスワード(確認)", max_length=256, widget=forms.PasswordInput(render_value=True, attrs={'class': 'form-control'}))
    name = forms.CharField(label="お名前", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))

class UserSearchForm(forms.Form):
    # product = forms.ModelChoiceField(models.Product.objects, label='商品')
    # amount = forms.IntegerField(min_value=1, max_value=10, label='個数')
    # category = forms.ModelChoiceField(models.Category.objects.order_by('category_id'), label='カテゴリ', to_field_name="category_id", initial='0')
    keyword = forms.CharField(label="会員ID", max_length=128, required = False)

class PurchaseSearchForm(forms.Form):
    year = (
        ('2017', 2017),('2018', 2018), ('2019', 2019),('2020', 2020),('2021', 2021),
    )
    month = (
        ('1', 1),('2', 2),('3', 3),('4', 4),('5', 5),('6', 6),
        ('7', 7),('8', 8),('9', 9),('10', 10),('11', 11),('12', 12),
    )
    day = (
        ('1', 1),('2', 2),('3', 3),('4', 4),('5', 5),('6', 6),('7', 7),('8', 8),('9', 9),('10', 10),
        ('11', 11),('12', 12),('13', 13),('14', 14),('15', 15),('16', 16),('17', 17),('18', 18),('19', 19),('20', 20),
        ('21', 21),('22', 22),('23', 23),('24', 24),('25', 25),('26', 26),('27', 27),('28', 28),('29', 29),('30', 30),
        ('31', 31),
    )
    keyword = forms.CharField(label="会員ID", max_length=128, required = False)
    from_y = forms.ChoiceField(choices=year, initial=2019, widget=forms.widgets.Select)
    from_m = forms.ChoiceField(choices=month, initial=1)
    from_d = forms.ChoiceField(choices=day, initial=1)
    to_y = forms.ChoiceField(choices=year, initial=2020, widget=forms.widgets.Select)
    to_m = forms.ChoiceField(choices=month, initial=12)
    to_d = forms.ChoiceField(choices=day, initial=31)

administrator/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic #継承すべきListViewをgenericモジュールに導入する
from shopping.models import Item, Purchase, PurchaseDetail #モデル、データ源を導入する
from account.models import User
from django.urls import reverse_lazy
from django.utils import timezone
from shopping.forms import SearchForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from . import forms
from . import models
import logging
import datetime

logger = logging.getLogger('login') # loggerを指定

def paginate_queryset(request, queryset, count):
    """Pageオブジェクトを返す。
    ページングしたい場合に利用してください。
    countは、1ページに表示する件数です。
    返却するPgaeオブジェクトは、以下のような感じで使えます。
        {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}">Prev</a>
        {% endif %}
    また、page_obj.object_list で、count件数分の絞り込まれたquerysetが取得できます。
    """
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj

def login(request):
    if request.session.get('is_admin', None):
        return redirect('/administrator')
    if request.method == 'POST':
        print("ok")
        login_form = forms.UserForm(request.POST) #ログインForm生成
        message = '入力した内容を再度確認してください'
        if login_form.is_valid():
            admin_id = login_form.cleaned_data.get('id')
            password = login_form.cleaned_data.get('password')
            try:
                admin = models.Admin.objects.get(admin_id=admin_id)
            except :
                message = 'この管理者ユーザが存在しません'
                return render(request, 'administrator/login.html', locals())
            if admin.password == password:
                request.session['is_admin'] = True #session書き込み
                logger.info('url:%s method:%s admin:%s login'% (request.path, request.method, admin.admin_id)) #log
                return redirect('/administrator')
            else:
                message = 'パスワードが正しくありません。'
                return render(request, 'administrator/login.html', locals())
        else:
            return render(request, 'administrator/login.html', locals())
    login_form = forms.UserForm()
    return render(request, 'administrator/login.html', locals())

def logout(request):
    if not request.session.get('is_admin', None):
        return redirect("/administrator/login/")
    request.session.flush()
    return redirect("/administrator/login/")

def register_admin(request):
    if request.session.get('is_admin', None): #ログインしていない状態確認
        return redirect('/administrator/')

    if request.method == 'POST':
        register_form = forms.RegisterForm(request.POST)
        message = "入力した内容を再度確認してください"
        if register_form.is_valid(): #form検査
            admin_id = register_form.cleaned_data.get('id')
            password1 = register_form.cleaned_data.get('password1')
            password2 = register_form.cleaned_data.get('password2')
            name = register_form.cleaned_data.get('name')

            if password1 != password2:
                message = '二回入力されたパスワードが一致しません。'
                return render(request, 'administrator/registerAdmin.html', locals())
            else:
                same_id_user = models.Admin.objects.filter(admin_id=admin_id)
                if same_id_user:
                    message = 'この管理者IDが登録済です。'
                    return render(request, 'administrator/registerAdmin.html', locals())
                new_admin = models.Admin()
                new_admin.admin_id = admin_id
                new_admin.password = password1
                new_admin.name = name
                new_admin.save()
                return render(request, 'administrator/registerAdminSuccess.html', locals())
        else:
            return render(request, 'administrator/registerAdmin.html', locals())
    register_form = forms.RegisterForm()
    return render(request, 'administrator/registerAdmin.html', locals())

class Index(generic.View):
    template_name = 'administrator/main.html'

    def get(self, request):
        if not request.session.get('is_admin', None):
            return redirect("/administrator/login/")
        search_form = SearchForm() #検索Form生成
        user_search_form = forms.UserSearchForm()
        purchase_search_form = forms.PurchaseSearchForm()
        context = {
            'search_form': search_form,
            'user_search_form': user_search_form,
            'purchase_search_form': purchase_search_form,
        }
        return render(request, self.template_name, context=context)

class ItemList(generic.ListView): #ListViewを定義し,generic.listviewを継承する
    model = Item #モデルを指定する
    context_object_name = 'item_list' #レンダリングテンプレートのcontext objectを定義し、デフォルトの名前はmodel_name_listであり、context_object_nameで上書きすることができる
    template_name = 'administrator/itemSearch.html' #指定しない場合は、デフォルトでmodel_name_list.htmlとなる
    # paginate_by = 5 #ページング
    def get(self, request):
        if not request.session.get('is_admin', None):
            return redirect("login/")
        queryset = Item.objects.all().order_by('-item_id')
        keyword = request.GET.get('keyword')
        category = int(request.GET.get('category'))
        if category == 0: #すべてのカテゴリ
            queryset = Item.objects.filter(name__contains=keyword) #filterフィルタの結果条件に一致するオブジェクトが複数ある
        else:
            queryset = Item.objects.filter(category_id=category,name__contains=keyword)
        page_obj = paginate_queryset(request, queryset, 3)
        context = {
            # 'item_list': queryset,
            'keyword': keyword,
            'category': category,
            'item_list': page_obj.object_list,
            'page_obj': page_obj,
        }
        return render(request, self.template_name, context=context)

class ItemCreate(generic.CreateView):
    model = Item #モデルを指定する
    template_name = 'administrator/item_form.html'    # 表オブジェクトのテンプレートページを追加する
    # success_url = reverse_lazy('administrator:item_list')
    success_url = '/administrator'
    fields = ['item_id', 'name', 'manufacturer', 'color', 'price', 'stock', 'recommended', 'category']
    def add(request):
        form = Item(request.POST or None)
        if form.is_valid():
            instance.save()
        context = {
            'form': form,
        }
        #有効なコミットがない場合は、元のページに残る
        return render(request, 'administrator/item_list.html',  context)

class ItemUpdate(generic.UpdateView):
    model = Item
    template_name = 'administrator/item_form.html'
    # success_url = reverse_lazy('administrator:')
    success_url = '/administrator'
    fields = ['name', 'manufacturer', 'color', 'price', 'stock', 'recommended', 'category']

class ItemDelete(generic.DeleteView):
    model = Item
    template_name = 'administrator/item_confirm_delete.html'
    success_url = reverse_lazy('administrator:')
    success_url = '/administrator'

class ItemDetail(generic.DetailView):
    model = Item   #modelをItemと指定し,Djangoに取得したいモデルがItemであることを伝えた。
    context_object_name = 'item_detail'   #取得したモデルリストのデータが保持する変数名を指定する。この変数はテンプレートに渡される。
    template_name = 'administrator/item_detail.html'
    def get_context_data(self, **kwargs):
        context = super(ItemDetail, self).get_context_data(**kwargs)
        context['now'] = timezone.now() #contextに追加
        return context

class UserList(generic.ListView):
    model = User
    context_object_name = 'user_list'
    template_name = 'administrator/userSearch.html'
    # paginate_by = 5 #ページング
    def get(self, request):
        queryset = User.objects.all().order_by('-user_id')
        keyword = request.GET.get('keyword')
        queryset = User.objects.filter(user_id__contains=keyword)
        context = {
            'user_list': queryset,
        }
        return render(request, self.template_name, context=context)

class UserUpdate(generic.UpdateView):
    model = User
    template_name = 'administrator/user_form.html'
    success_url = reverse_lazy('administrator:index')
    fields = ['user_id', 'name', 'password','address']

class UserDelete(generic.DeleteView):
    model = User
    template_name = 'administrator/user_confirm_delete.html'
    success_url = reverse_lazy('administrator:index')

class PurchaseList(generic.ListView):
    model = Purchase
    context_object_name = 'purchase_list'
    template_name = 'administrator/purchaseSearch.html'
    # paginate_by = 5 #ページング
    def get(self, request):
        queryset = Purchase.objects.all().order_by('-purchase_id')
        # 検索対象のユーザ名取得
        keyword = request.GET.get('keyword')
        start = datetime.date(int(request.GET.get('from_y')), int(request.GET.get('from_m')), int(request.GET.get('from_d')))
        end = datetime.date(int(request.GET.get('to_y')), int(request.GET.get('to_m')), int(request.GET.get('to_d')))
        end = end + datetime.timedelta(days=1)#end日付を＋1
        queryset = Purchase.objects.filter(user__user_id__icontains=keyword,
            booked_date__range=[start, end])    #外部キーならmodel__class__icontains=
        context = {
            'purchase_list': queryset,
        }
        if queryset:
            queryset_detail = PurchaseDetail.objects.filter(purchase__user__user_id__icontains=keyword,
                purchase__booked_date__range=[start, end])
            if queryset_detail:
                context['detail_list'] = queryset_detail
        print(context)
        return render(request, self.template_name, context=context)

class PurchaseDelete(generic.DeleteView):
    model =Purchase
    template_name = 'administrator/purchase_confirm_delete.html'

administrator/templates/administrator/deleteItemCommit.html
<html>
	<head>
		<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
		<title>商品の削除完了</title>
		<link rel='stylesheet' type='text/css' href='style.css' />
	</head>
	<body>
		<h3>以下の商品の削除を完了しました。</h3>
		<br />
		<table>
			<tr>
				<th>商品名</th>
				<td>麦わら帽子</td>
			</tr>
			<tr>
				<th>商品の色</th>
				<td>黄色</td>
			</tr>
			<tr>
				<th>メーカー名</th>
				<td>日本帽子製造</td>
			</tr>
			<tr>
				<th>カテゴリ</th>
				<td>帽子</td>
			</tr>
			<tr>
				<th>オススメ</th>
				<td>オススメしない</td>
			</tr>
			<tr>
				<th>価格</th>
				<td>4980 円</td>
			</tr>
			<tr>
				<th>在庫数</th>
				<td>12 個</td>
			</tr>
		</table>
		<br />
		<a href='main.html'>管理者メインページ</a>へ<br />
	</body>
</html>

administrator/templates/administrator/deleteItemConfirm.html
<html>
	<head>
		<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
		<title>商品の削除確認</title>
		<link rel='stylesheet' type='text/css' href='style.css' />
	</head>
	<body>
		<h3>以下の商品を削除しますか？</h3>
		<br />
		<form action='deleteItemCommit.html' method='POST'>
			<table>
				<tr>
					<th>商品名</th>
					<td>麦わら帽子</td>
				</tr>
				<tr>
					<th>商品の色</th>
					<td>黄色</td>
				</tr>
				<tr>
					<th>メーカー名</th>
					<td>日本帽子製造</td>
				</tr>
				<tr>
					<th>カテゴリ</th>
					<td>帽子</td>
				</tr>
				<tr>
					<th>オススメ</th>
					<td>オススメしない</td>
				</tr>
				<tr>
					<th>価格</th>
					<td>4980 円</td>
				</tr>
				<tr>
					<th>在庫数</th>
					<td>12 個</td>
				</tr>
				<tr>
					<td colspan='2'><input type='submit' value='削除' /></td>
				</tr>
			</table>
		</form>
		<a href='main.html'>管理者メインページ</a>へ<br />
	</body>
</html>

administrator/templates/administrator/deletePurchaseConfirm.html
<html>
	<head>
		<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
		<title>注文のキャンセル</title>
		<link rel='stylesheet' type='text/css' href='style.css' />
	</head>
	<body>
		<h3>以下の注文をキャンセルしてよろしいですか？</h3>
		<br />
		<table>
			<tr>
				<th>注文者ID</th>
				<td>someone@example.com</td>
			</tr>
			<tr>
				<th>注文日</th>
				<td>2014/3/15</td>
			</tr>
			<tr>
				<th>購入商品</th>
				<td>
					<table>
						<tr>
							<th>商品名</th>
							<th>色</th>
							<th>メーカー</th>
							<th>単価</th>
							<th>数量</th>
						</tr>
						<tr>
							<td>麦わら帽子</td>
							<td>黄色</td>
							<td>日本帽子製造</td>
							<td>4980円</td>
							<td>2 個</td>
						</tr>
						<tr>
							<td>子ども用麦わら帽子</td>
							<td>赤</td>
							<td>東京帽子店</td>
							<td>2980円</td>
							<td>3 個</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<th>配送先</th>
				<td>自宅</td>
			</tr>
			<tr>
				<td colspan='2'>
					<form action='deletePurchaseCommit.html' method='POST'>
						<input type='hidden' name='purchaseId' value='1234' />
						<input type='submit' value='キャンセル' /><br />
					</form>
				</td>
			</tr>
		</table>
		<br />
		<a href='main.html'>管理者メインページ</a>へ<br />
	</body>
</html>

administrator/templates/administrator/deleteUserCommit.html
<html>
	<head>
		<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
		<title>会員の削除完了</title>
		<link rel='stylesheet' type='text/css' href='style.css' />
	</head>
	<body>
		<h3>以下の会員を削除しました。</h3>
		<br />
		<table>
			<tr>
				<th>会員ID</th>
				<td>someone@example.com</td>
			</tr>
			<tr>
				<th>名前</th>
				<td>テスト太郎</td>
			</tr>
			<tr>
				<th>住所</th>
				<td>東京都千代田区１－１－１</td>
			</tr>
		</table>
		<br />
		<a href='main.html'>管理者メインページ</a>へ<br />
	</body>
</html>

administrator/templates/administrator/deleteUserConfirm.html
<html>
	<head>
		<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
		<title>会員の削除確認</title>
		<link rel='stylesheet' type='text/css' href='style.css' />
	</head>
	<body>
		<h3>以下の会員を削除しますか？</h3>
		<br />
		<table>
			<tr>
				<th>会員ID</th>
				<td>someone@example.com</td>
			</tr>
			<tr>
				<th>名前</th>
				<td>テスト太郎</td>
			</tr>
			<tr>
				<th>住所</th>
				<td>東京都千代田区１－１－１</td>
			</tr>
			<tr>
				<form action='deleteUserCommit.html' method='POST'>
					<td colspan='2'><input type='submit' value='削除' /></td>
				</form>
			</tr>
		</table>
		<br />
		<a href='main.html'>管理者メインページ</a>へ<br />
	</body>
</html>

administrator/templates/administrator/item_detail.html
<h1>商品名：{{ object.name }}</h1>
<h2>商品番号：{{ object.item_id }}</h2>
<p>商品名：{{ object.name }}</p>
<p>商品カテゴリ： {{ object.category }}</p>
<p>メーカー名：{{ object.manufacturer }}</p>
<p>商品の色：{{ object.color }}</p>
<p>価格： {{ object.price }}</p>
<p>在庫： {{ object.stock }}</p>
<p>おすすめ： {{ object.recommended }}</p>

administrator/templates/administrator/item_form.html
<title>Title</title>
<form method="post">
    <table>
        {% csrf_token %}
        {{ form }}
    </table>
<input type="submit" value="確認" />
</form>

administrator/templates/administrator/item_list.html
<ul>
    {% for item in item_list %}
    <a href="{% url "administrator:item_detail" item.item_id %}">{{ item.name }}</a>
    <li>{{ item.item_id }} &nbsp &nbsp {{ item.name }} &nbsp &nbsp{{ item.manufacturer }}&nbsp &nbsp{{ item.category }} &nbsp &nbsp
        {{ item.color }} &nbsp &nbsp{{ item.price }}&nbsp &nbsp{{ item.stock }} &nbsp &nbsp{{ item.recommended }}:
    <a href="{% url "administrator:item_update" item.item_id %}">修改</a>
    <a href="{% url "administrator:item_delete" item.item_id %}">删除</a>
    </li>&nbsp
    {% endfor %}
</ul>
{% if is_paginated %}
<div class="pagination center-block">
    <span>共{{ page_obj.paginator.num_pages }}页</span>
    <span id="paging" class="step-links" style="display: block;text-align: center">
        {% if page_obj.has_previous %}
        <span><a href="?page={{ page_obj.previous_page_number }}">上一页</a></span>
        {% endif %}
        <span class="active">{{ page_obj.number }}</span>
        {% if page_obj.has_next %}
        <span><a href="?page={{ page_obj.next_page_number }}">下一页</a></span>
        {% endif %}
    </span>
</div>
{% endif %}
<a href="{% url "administrator:item_add" %}">新增</a>

administrator/templates/administrator/purchaseSearch.html
{% load static %}
<html>
	<head>
		<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
		<title>購入履歴一覧</title>
		<link rel='stylesheet' type='text/css' href='{% static "shopping/css/style.css" %}' />
	</head>
	<body>
		<h3>購入履歴の一覧</h3>
		<br />
		<table>
			<tr>
				<th>購入者ID</th>
				<th>注文日</th>
				<th>購入商品</th>
				<th>配送先</th>
				<th></th>
			</tr>
			{% for object in purchase_list %}
			<tr>
				<td>{{ object.user_id }}</td>
				<td>{{ object.booked_date }}</td>
				<td>
					<table>
						<tr>
							<th>商品名</th>
							<th>色</th>
							<th>メーカー</th>
							<th>単価</th>
							<th>数量</th>
						</tr>
						{%for detail in detail_list%}
							{%ifequal object.purchase_id  detail.purchase_id %}
							<tr>
								<td>{{ detail.item.name }}</td>
								<td>{{ detail.item.color }}</td>
								<td>{{ detail.item.manufacturer }}</td>
								<td>{{ detail.price }}円</td>
								<td>{{ detail.amount }}個</td>
							</tr>
							{% endifequal %}
						{% endfor %}
					</table>
				</td>
				<td>{{ object.destination }}</td>
				<td><a href='{% url "administrator:purchase_delete" object.purchase_id %}'>キャンセル</a></td>
			</tr>
			{% endfor %}
		</table>
		<br /><br />
		<a href='{% url "administrator:index" %}'>管理者メインページ</a>へ<br />
	</body>
</html>

administrator/templates/administrator/registerAdmin.html
{% load static %}
<html>
	<head>
		<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
		<title>管理者登録</title>
		<link rel='stylesheet' type='text/css' href='{% static "account/css/style.css" %}' />
	</head>
	<body>
		<h3>管理者情報を入力してください。</h3>
		<br />
		<form action='/administrator/registerAdmin/' method='POST'>
			{% csrf_token %}
			<table>
				{{ register_form }}
				<tr>
					<td colspan='2'><input type='submit' value='登録確認' /></td>
				</tr>
			</table>
			{% if register_form.captcha.errors %}
			<div>{{ register_form.captcha.errors }}</div>
			{% elif message %}
			<div>{{ message }}</div>
			{% endif %}
		</form>
		<a href='/administrator/'>管理者メインページ</a>へ<br />
	</body>
</html>

administrator/templates/administrator/registerItemConfirm.html
<html>
	<head>
		<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
		<title>商品の登録確認</title>
		<link rel='stylesheet' type='text/css' href='style.css' />
	</head>
	<body>
		<h3>以下の商品を登録しますか？</h3>
		<br />
		<form action='registerItemCommit.html' method='POST'>
			<table>
				<tr>
					<th>商品名</th>
					<td>シルクハット</td>
				</tr>
				<tr>
					<th>商品の色</th>
					<td>黒</td>
				</tr>
				<tr>
					<th>メーカー名</th>
					<td>イギリス屋</td>
				</tr>
				<tr>
					<th>カテゴリ</th>
					<td>帽子</td>
				</tr>
				<tr>
					<th>オススメ</th>
					<td>オススメしない</td>
				</tr>
				<tr>
					<th>価格</th>
					<td>20000 円</td>
				</tr>
				<tr>
					<th>在庫数</th>
					<td>1000 個</td>
				</tr>
				<tr>
					<td colspan='2'><input type='submit' value='登録' /></td>
				</tr>
			</table>
		</form>
		<a href='main.html'>管理者メインページ</a>へ<br />
	</body>
</html>

administrator/templates/administrator/updateUserCommit.html
<html>
	<head>
		<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
		<title>会員情報の更新完了</title>
		<link rel='stylesheet' type='text/css' href='style.css' />
	</head>
	<body>
		<h3>以下の会員情報で更新しました。</h3>
		<br />
		<table>
			<tr>
				<th>会員ID</th>
				<td>someone@example.com</td>
			</tr>
				<th>パスワード</th>
				<td>********</td>
			</tr>
			<tr>
				<th>お名前</th>
				<td>テスト太郎</td>
			</tr>
			<tr>
			<tr>
				<th>ご住所</th>
				<td>東京都千代田区１－１－１</td>
			</tr>
		</table><br />
		<a href='main.html'>管理者メインページ</a>へ<br />
	</body>
</html>

administrator/templates/administrator/updateUserConfirm.html
<html>
	<head>
		<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
		<title>会員情報の更新</title>
		<link rel='stylesheet' type='text/css' href='style.css' />
	</head>
	<body>
		<h3>以下の会員情報で更新しますか？</h3>
		<br />
		<form action='updateUserCommit.html' method='POST'>
			<table>
				<tr>
					<th>会員ID</th>
					<td>someone@example.com</td>
				</tr>
				<tr>
					<th>パスワード</th>
					<td>********</td>
				</tr>
				<tr>
					<th>お名前</th>
					<td>テスト太郎</td>
				</tr>
				<tr>
					<th>ご住所</th>
					<td>東京都千代田区１－１－１</td>
				</tr>
				<tr>
					<td colspan='2'><input type='submit' value='変更' /></td>
				</tr>
			</table>
		</form>
		<a href='main.html'>管理者メインページ</a>へ<br />
	</body>
</html>

administrator/templates/administrator/user_form.html
<title>会員情報変更</title>
<form method="post">
    <table>
        {% csrf_token %}
        {{ form }}
    </table>
<input type="submit" value="変更確認" />
</form>